version: '3.3'
services:
  app:
    image: python:3.10-bullseye
    command: bash -c "bash <(curl -s https://sh.samliu.dev/github_docker.sh)"
    working_dir: /src
    volumes:
      - app-source:/src
      - app-data:/data
    networks:
      - app-net
    environment:
      - RUN_COMMAND=python3 main.py
      - BUILD_COMMAND=python3 -m pip install -r requirements.txt
      - GIT_REPO=https://${GITHUB_TOKEN}@github.com/someuser/some-repo
      - GIT_BRANCH=main
      
      - ANOTHER_ENV_VAR
      - ANOTHER_ENV_VAR2
    restart: "always"
      
volumes:
  app-source:
  app-data:

networks:
  app-net:
    driver: bridge
